### PR TITLE
DO NOT MERGE: See if labeler works (try 4)

### PR DESCRIPTION
**Pull request by pllim**
### Description

Like #2

### CODE REVIEW

**Comment by pllim** [comment]
What...? Where did `wcs`, `utils`, and `visualization` come from?!

**Comment by saimn** [comment]
I guess that when excluding path, like for wcs/wcsapi, you need to use `-all: [...]`.
By default it's `-any: ...`.

**Comment by pllim** [comment]
Thanks. I'll have to wrap my head around the `any`/`all` logic when I come back to this. 😸

**Comment by saimn** [comment]
Well, I don't understand their logic :
```
# Add 'source' label to any change to src files within the source dir EXCEPT for the docs sub-folder
source:
- any: ['src/**/*', '!src/docs/*']

# Add 'frontend` label to any change to *.js files as long as the `main.js` hasn't changed
frontend:
- any: ['src/**/*.js']
  all: ['!src/main.js']
```

**Pull request closed without merging**
